name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          # Your build commands here (if necessary)
          # For example, if using npm:
          npm install
          npm run build

      - name: Deploy
        uses: actions/deploy@v1
        with:
          provider: pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          folder: build # Replace with your build output directory
